### ISSUE TITLE
Question: Doctrine Extensions configuration

### ISSUE THREAD

**Issue by remarkusable** [FoxxMD/laravel-doctrine#5]
any plan on making Doctrine Extensions installation configurable from the config file?

**Comment by FoxxMD** [comment]
Are you referring to [this](https://github.com/Atlantic18/DoctrineExtensions)? I haven't seen this package before! I like the functionality it's offering. I'm not making any promises but if I find the time I will definitely try and integrate it!

**Comment by remarkusable** [comment]
[that](https://github.com/Atlantic18/DoctrineExtensions) extensions give nice features, but currently i want to use [this](https://github.com/beberlei/DoctrineExtensions)

currently what i did is:

``` php
$config = $em->getConfiguration();
$config->addCustomNumericFunction('ROUND', 'DoctrineExtensions\Query\Mysql\Round');
```

but it would be nice if we can set this in the config file like in the [example](https://github.com/beberlei/DoctrineExtensions/blob/master/config/mysql.yml):

```
doctrine:
     orm:
         dql:
             numeric_functions:
                    round: DoctrineExtensions\Query\Mysql\Round
```

then add the configuration on LaravelDoctrineServiceProvider. what do you think?
